version: '3.8'

services:
  eureka:
    build:
      context: ./eurekaserver
    container_name: eureka
    ports:
      - "8761:8761"
    networks:
      - app-network

  apigateway:
    build:
      context: ./apigateway
    container_name: apigateway
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - eureka
      - mysql
      - student-service
      - address-service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_PASSWORD: root
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 30s
      retries: 3


  student-service:
    build:
      context: ./student-service
    container_name: student-service
    ports:
      - "8081:8081"
    networks:
      - app-network
    depends_on:
      - mysql
      - eureka
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/studentdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/

  address-service:
    build:
      context: ./address-service
    container_name: address-service
    ports:
      - "8083:8083"
    networks:
      - app-network
    depends_on:
      - mysql
      - eureka
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/addressdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/




networks:
  app-network:
    driver: bridge
