spring:
  main:
    web-application-type: reactive
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: address-service
          uri: lb://address-service
          predicates:
            - Path=/api/address/**
        - id: student-service
          uri: lb://student-service
          predicates:
            - Path=/api/student/**
      cors:
        allowed-origins:
            - "*"  # Allow all origins
        allowed-methods:
          - "GET"
          - "POST"
          - "PUT"
          - "DELETE"
          - "PATCH"
          - "OPTIONS"
        allowed-headers:
          - "*"  # Allow all headers
        allow-credentials: false

  server:
    port: 9090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
