spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: address-service
          uri: lb://ADDRESS-SERVICE
          predicates:
            - Path=/api/address/**
        - id: student-service
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/api/student/**
  server:
    port: 9090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
