spring:
  application:
    name: student-service
  datasource:
    url: 'jdbc:mysql://localhost:3306/studentdb?useUnicode'
    username: root
    password: root
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL8Dialect
server:
  port: '8081'
eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
    register-with-eureka: true
    fetch-registry: true
address:
  service:
    url: 'http://localhost:8083'
