spring:
  cloud:
      gateway:
        cors:
          allowed-origins: "http://localhost:8077"  # Add your frontend's URL here
          allowed-methods: "GET, POST, PUT, DELETE"
          allowed-headers: "*"
          allow-credentials: true
  application:
    name: student-service
  datasource:
    url: 'jdbc:mysql://localhost:3306/studentdb?useUnicode'
    username: root
    password: root
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
server:
  port: '8081'
eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
    register-with-eureka: true
    fetch-registry: true
address:
  service:
    url: 'http://localhost:8083'
