spring:
  cloud:
    gateway:
      cors:
        allowed-origins: "http://localhost:8077"  # Add your frontend's URL here
        allowed-methods: "GET, POST, PUT, DELETE"
        allowed-headers: "*"
        allow-credentials: true
  application:
    name: address-service
  datasource:
    url: jdbc:mysql://mysql:3306/addressdb?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL8Dialect
server:
  port: '8083'
eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka/'
